Pose to signwriting segmentation
sign-language-processing/signwriting-transcription pull request #7
Opened 2024-02-21 23:46 UTC by RotemZilberman

- adding a segmentation option to the bin file
 - change the load_data to enable segment data

2024-02-22 07:08 UTC, AmitMY requested changes

2024-02-22 07:08 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/data/prepare_poses.py
> +            instance[3] = 'train' if instance[3] == 'test' else instance[3]
you are *training* on the test data? this is really bad. you should filter out the test data

2024-02-22 07:08 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/bin.py
> +    parser.add_argument('--strategies', required=False, type=str, default='tight',
should be `strategy`, no need for `required=False` because there is `default`, `help` can be more helpful, "segmentation strategy to use"

2024-02-22 07:08 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/bin.py
> +        end = sign_annotations[index + 1][0] if index + 1 < len(sign_annotations) else None
this code is very messy and not very readable, or at all documented:
what is a wide strategy? what is a tight strategy?

2024-02-22 07:08 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/bin.py
> +            np_pose = pose_to_matrix(temp_pose_path, segment[0] - (segment[0] - start) * 0.25
you are loading the pose from disk as many times as there are segments. maybe `pose_to_matrix` should accept a pose object as well as a path?

2024-02-22 07:08 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/data/datasets_pose.py
> +    pose = pose[ms2frame(start_ms, frame_rate):ms2frame(end_ms, frame_rate)] if (
you should probably split this in three lines:
```python
start_frame = ms2frame(start_ms, frame_rate)
end_frame = ms2frame(end_ms, frame_rate) if end_ms is not None else None
pose = pose[start_frame:end_frame]
```

2024-02-22 18:17 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/bin.py
> +            np_pose = pose_to_matrix(temp_pose_path, segment[0] - (segment[0] - start) * 0.25
i fixed that

2024-02-23 09:20 UTC, RotemZilberman commented on signwriting_transcription/pose_to_signwriting/bin.py
> +            temp_file.unlink()
I saw on the internet that the with section is handling the cleanup automatically

2024-02-23 11:47 UTC, AmitMY requested changes

2024-02-23 11:47 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/bin.py
no need for `temp_dir.cleanup()`?
either add it, or remove the print

2024-02-23 11:47 UTC, AmitMY commented on signwriting_transcription/pose_to_signwriting/bin.py
> +def preprocessing_signs(preprocessed_pose: Pose, sign_annotations: list, strategy: str, temp_dir: str):
good, just that this should be `preprocess_signs` (as an imperative)

2024-02-26 06:50 UTC, AmitMY approved these changes

2024-02-26 06:50 UTC, merged